---
collections:
  - name: community.general
    version: 8.1.0
  - name: community.docker
    version: 3.10.3
  - name: community.mysql
    version: 3.13.0
  - name: community.postgresql
    version: 3.12.0
  - name: amazon.aws
    version: 9.3.0
