# Create a DNS record pointing to the host
- name: Create DNS record
  amazon.aws.route53:
    state: "{{ service_enabled | ternary('present', 'absent') }}"
    overwrite: true
    zone: "{{ service_dns.zone }}"
    record: "{{ service_dns.name }}.{{ service_dns.zone }}"
    type: CNAME
    value: "{{ ansible_host }}"
    ttl: 60