---
- name: Create service databases
  mysql_db:
    state: present
    name: "{{ service_db_name }}"
    login_host: "{{ service_db_host }}"
    login_user: "{{ service_db_login_user }}"
    login_password: "{{ service_db_login_pass }}"

- name: Create DB service accounts 
  mysql_user:
    state: present
    column_case_sensitive: true
    name: "{{ service_db_user }}"
    password: "{{ service_db_password }}"
    host: '%'
    priv: "{{ service_db_name }}.*:ALL"
    login_host: "{{ service_db_host }}"
    login_user: "{{ service_db_login_user }}"
    login_password: "{{ service_db_login_pass }}"
