# Create top-level directory for the bind mounts
- name: Create main directory
  file:
    path: "{{ service_mounts_path }}/{{ service_dns }}.{{ service_dns_zone }}"
    state: directory

# Create one directory for each bind mount exposed as a volume
- name: Create sub-directories
  file:
    path: "{{ service_mounts_path }}/{{ service_dns }}.{{ service_dns_zone }}/{{ item | basename }}"
    state: directory
  loop: "{{ service_mounts }}"
